### PR TITLE
perimeter-sub

### PR DESCRIPTION
**Pull request by dashing-dev**
qbasic program in sub procedure to calculate perimeter of rectangle

### CODE REVIEW

**Comment by dashing-dev** [comment]
why don't you create repo for c language too?

**Comment by Logicwhiz** [comment]
i am not so proficient in c so.

**Comment by dashing-dev** [comment]
create one i will help

**Comment by Logicwhiz** [comment]
ok sure

**Comment by dashing-dev** [comment]
please do

**Pull request merged**
