### PR TITLE
armstrong

### PR DESCRIPTION
**Pull request by dashing-dev**
new qbasic code to check armstrong or not

### CODE REVIEW

**Comment by Logicwhiz** [comment]
please add more comments in the program

**Comment by dashing-dev** [comment]
what type of comments?

**Comment by Logicwhiz** [comment]
something descriptive

**Comment by dashing-dev** [comment]
for every function ?

**Comment by Logicwhiz** [comment]
yes

**Comment by dashing-dev** [comment]
i will try

**Comment by Logicwhiz** [comment]
please use easy format

**Comment by dashing-dev** [comment]
sorry , can you please explain it more ?

**Comment by Logicwhiz** [comment]
your program are not in the level of class 10 books

**Comment by dashing-dev** [comment]
ok i will take care about it

**Comment by dashing-dev** [comment]
please merge it

**Pull request merged**
