### PR TITLE
palindrome

### PR DESCRIPTION
**Pull request by dashing-dev**

### CODE REVIEW

**Comment by Logicwhiz** [comment]
doesn't looks like a 10 class program

**Comment by dashing-dev** [comment]
> doesn't looks like a 10 class program

what should i do?

**Comment by Logicwhiz** [comment]
use simpler logics according to class 9-10 level

**Comment by dashing-dev** [comment]
OK

**Comment by Logicwhiz** [comment]
i  am going to merge this . Follow my guides from next time . Happy coding

**Pull request merged**
