### PR TITLE
hexa to decimal

### PR DESCRIPTION
**Pull request by dashing-dev**
program to convert hexadecimal to decimal

### CODE REVIEW

**Comment by Logicwhiz** [comment]
i have created c repo too

**Comment by dashing-dev** [comment]
ok i will check

**Comment by dashing-dev** [comment]
btw , thanks for taking my suggestion

**Comment by Logicwhiz** [comment]
always there for anyone requesting valid chnages

**Comment by dashing-dev** [comment]
thats the spirit

**Comment by Logicwhiz** [comment]
lets connect

**Comment by dashing-dev** [comment]
sure

**Comment by Logicwhiz** [comment]
socials?

**Comment by dashing-dev** [comment]
i haved linked in my readme file please check

**Comment by Logicwhiz** [comment]
sure

**Comment by Logicwhiz** [comment]
you have provided life for this repo

**Comment by dashing-dev** [comment]
haha , my pleasure to serve this awesome movement

**Comment by Logicwhiz** [comment]
thanks again

**Comment by dashing-dev** [comment]
no need to thank me bro

**Comment by dashing-dev** [comment]
please merge this

**Pull request merged**
